# A sample Gemfile
source "http://rubygems.org"

# for testing/demo
gem "whenever"
gem "ZenTest"
gem "wirble"
gem "activesupport"
gem "i18n"
gem "rake"
gem "echoe"

# for testing
gem "shoulda"
gem "mocha"
gem "colorize"

# libraries needed
gem "nokogiri"
gem "httparty"
gem "builder"



gem "ansi"
gem "turn", :git => "https://github.com/TwP/turn"
